using ColossalFramework;
using HarmonyLib;
using QCommonLib;

namespace NetworkAnarchy.Patches
{
    class Utils
    {
        /// <summary>
        /// Remove building limiting errors for networks
        /// </summary>
        /// <param name="errors">The errors generated by the vanilla game</param>
        /// <returns>The pruned down errors</returns>
        internal static ToolBase.ToolErrors YeetLimits(ToolBase.ToolErrors errors)
        {
            if (NetworkAnarchy.Anarchy)
            {
                errors &= ~ToolBase.ToolErrors.CanalTooClose;
                errors &= ~ToolBase.ToolErrors.CannotBuildOnWater;
                errors &= ~ToolBase.ToolErrors.HeightTooHigh;
                errors &= ~ToolBase.ToolErrors.ShoreNotFound;
                errors &= ~ToolBase.ToolErrors.SlopeTooSteep;
                errors &= ~ToolBase.ToolErrors.WaterNotFound;
            }
            return errors;
        }
    }

    /// <summary>
    /// Make ship and airplane paths bulldozeable 
    /// </summary>
    [HarmonyPatch(typeof(DefaultTool), "GetService")]
    public static class DT_GetService
    {
        public static void Postfix(ref ToolBase.RaycastService __result)
        {
            if (QCommon.Scene != QCommon.SceneTypes.Game) return;

            if (Singleton<InfoManager>.instance.CurrentMode == InfoManager.InfoMode.Transport)
            {
                __result.m_itemLayers |= ItemClass.Layer.AirplanePaths | ItemClass.Layer.ShipPaths;
            }
        }
    }

    /// <summary>
    /// Allow ship and airplane paths to be built outside the purchased tiles
    /// </summary>
    [HarmonyPatch(typeof(GameAreaManager), "QuadOutOfArea")]
    public static class GAM_QuadOutOfArea
    {
        public static bool Prefix(ref bool __result)
        {
            if (!(Singleton<ToolController>.instance.CurrentTool is NetTool)) return true;

            NetTool netTool = (NetTool)Singleton<ToolController>.instance.CurrentTool;
            NetInfo prefab = netTool.Prefab;

            if (prefab.name == "Ship Path" || prefab.name == "Airplane Path")
            {
                __result = false;
                return false;
            }
            return true;
        }
    }
}
